### PR TITLE
fix: BadOraLocationResponse error

### PR DESCRIPTION
**Pull request by dyudyunov**
Refactor the locationId constant for the subdirectory-based deployments support.

Exclude the MFE's `PUBLIC_PATH` from the constant.

The `window.location.pathname` example:
```
<PUBLIC_PATH>block-v1:oragrading+oragrading+oragrading+type@openassessment+block@ee217e897a954c1faa3b29317da0f2e7
```
Where the `PUBLIC_PATH` could be:
- `'/'` - for subdomain-based deployments (default)
- `'/mfe-specifix-public-path/'` - for subdirectory-based deployments

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dyudyunov!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by dyudyunov** [comment]
@mphilbrick211 hi!
This one is ready for review!)

**Comment by mphilbrick211** [comment]
Thanks, @dyudyunov - I will help get the tests running for you.

**Comment by e0d** [comment]
@dyudyunov Looks like this branch is out of date with base.  Can you update?  I notice failing Node CI tests, but that may be rectified by rebasing.

**Comment by dyudyunov** [comment]
> @dyudyunov Looks like this branch is out of date with base. Can you update? I notice failing Node CI tests, but that may be rectified by rebasing.

Rebase is done)

**Comment by dyudyunov** [comment]
@e0d I've checked the related Olive PR and found out that the test failure is probably isn't connected to an outdated branch.

I'll check it in detail and notify you about the results

**Comment by dyudyunov** [comment]
@e0d 
I've refactored the test, please run checkers one more time

**Comment by e0d** [comment]
@dyudyunov tests look good.

**Comment by mphilbrick211** [comment]
Hi @mattcarter - would you mind taking a look at this and merging if it's good-to-go? Thanks!

**Comment by dyudyunov** [comment]
This PR fixes the same problem as the https://github.com/openedx/frontend-app-ora-grading/pull/146 do

So one of them will be merged while the other will be closed

**Comment by mphilbrick211** [comment]
Hi @mattcarter - friendly ping on this. Please review and merge if this looks good to you. Thanks!

**Comment by mphilbrick211** [comment]
> Hi @mattcarter - friendly ping on this. Please review and merge if this looks good to you. Thanks!

Apologies for the extra ping, @mattcarter - I see I left a comment just a couple days ago.

**Comment by mphilbrick211** [comment]
Hi @mattcarter - friendly ping on getting this merged. Thanks!

**Comment by dyudyunov** [comment]
rebased on the master branch and created a backport to palm https://github.com/openedx/frontend-app-ora-grading/pull/181

**Comment by mphilbrick211** [comment]
Hi @openedx/content-aurora - just checking to see if someone could please review/merge this for us? Thanks!

**Review by arbrandes — APPROVED** [review]
Code looks good, and it works!  Approved!

**Comment by openedx-webhooks** [comment]
@dyudyunov 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-ora-grading&entry.867055334=https://github.com/openedx/frontend-app-ora-grading/pull/167&entry.1484655318=https://github.com/dyudyunov&entry.752974735=2023-02-28+10:36&entry.1917517419=2023-05-15+13:37&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
