### PR TITLE
fix: decodeURIComponent for locationId 

### PR DESCRIPTION
**Pull request by vunguyen-dmt**
The current code is wrong for this case (localtion id contains characters like: Đ) :
[https://apps.demo.openedx.overhang.io/ora-grading/block-v1:ORG+Đ001+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f](https://apps.demo.openedx.overhang.io/ora-grading/block-v1:ORG+%C4%90001+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f)

Current code:

```
window.location.pathname.replace(getConfig().PUBLIC_PATH, '') = 
block-v1:ORG+%C4%90+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f
```
This PR code
```
decodeURIComponent(window.location.pathname).replace('/ora-grading/', '') =
block-v1:ORG+Đ+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f
```
The localtionId is used in [initialize request](https://github.com/openedx/frontend-app-ora-grading/blob/master/src/data/services/lms/api.js)
{LMS_BASE_URL}/api/ora_staff_grader/initialize?oraLocation={locationId}

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vunguyen-dmt!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by vunguyen-dmt** [comment]
Signed CLA for github username: vunguyen-dmt.

**Comment by mphilbrick211** [comment]
Hi @openedx/content-aurora! Would some be able to review/merge this for us? Thanks!

**Comment by mphilbrick211** [comment]
Hi @openedx/content-aurora, just checking in on this :)

**Comment by leangseu-edx** [comment]
I am confuse for what this pr suppose to do?

```
const url = 'https://apps.demo.openedx.overhang.io/ora-grading/block-v1:ORG+Đ001+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f'
decodeURIComponent(url) === url
```

**Comment by vunguyen-dmt** [comment]
Hi @leangseu-edx.
If you paste the URL to a web browser and try **window.location.pathname** and **decodeURIComponent(window.location.pathname)** they're two different results. The one without decodeURIComponent caused me errors in my course.

My courses were created back in Maple or Lilac through course_run API so some of them may have characters not from [A-z-az0-9-_.].

I believe in the current version (Palm) if courses were created in the web UI, they should not have any problems with decoding URLs.

If this app was created with an assumption that course id only contains [A-z-az0-9_-.] characters then this PR is not needed.
But if somewhere in the past or in the future this assumption was not true then it's safer to decodeURIComponent.

**Comment by leangseu-edx** [comment]
Can you update `src/data/constants/app.test.js`?

```js
import * as platform from '@edx/frontend-platform';
import * as constants from './app';

jest.unmock('./app');

jest.mock('@edx/frontend-platform', () => {
  const PUBLIC_PATH = '/test-public-path/';
  return {
    getConfig: () => ({ PUBLIC_PATH }),
    PUBLIC_PATH,
  };
});

describe('app constants', () => {
  test('route path draws from public path and adds courseId', () => {
    expect(constants.routePath()).toEqual(`${platform.PUBLIC_PATH}:courseId`);
  });
  describe('locationId', () => { 
    const domain = 'https://example.com';

    test('returns trimmed pathname', () => {
      const old = window.location;
      Object.defineProperty(window, "location", {
        value: new URL(`${domain}${platform.PUBLIC_PATH}somePath.jpg`),
        writable: true,
      });
      expect(constants.locationId()).toEqual(window.location.pathname.replace(platform.PUBLIC_PATH, ''));
      window.location = old;
    });
    test('handle none-standard characters pathName', () => {
      const old = window.location;
      const noneStandardPath = `${platform.PUBLIC_PATH}ORG+%C4%90+2023`;
      const expectedPath = `${platform.PUBLIC_PATH}ORG+Đ+2023`;
      Object.defineProperty(window, "location", {
        value: new URL(`${domain}${noneStandardPath}`),
        writable: true,
      });
      expect(noneStandardPath).not.toEqual(expectedPath);
      expect(constants.locationId()).toEqual(expectedPath.replace(platform.PUBLIC_PATH, ''));
      window.location = old;
    });
  });
});
```

**Comment by vunguyen-dmt** [comment]
Thanks! I updated it.

**Comment by leangseu-edx** [comment]
Please update the entire file. I added another test specifically for this one and the previous test wasn't working properly.

**Comment by mphilbrick211** [comment]
Hi @leangseu-edx! Would you mind enabling tests again for this PR?

**Comment by mphilbrick211** [comment]
Hi @vunguyen-dmt! It looks like there is a failing test - would you mind having a look? Thanks!

**Comment by mphilbrick211** [comment]
> Hi @vunguyen-dmt! It looks like there is a failing test - would you mind having a look? Thanks!

Hi @vunguyen-dmt! Just following up on this :)

**Comment by vunguyen-dmt** [comment]
I can do some JavaScript, but I don't know much about writing Reactjs unit tests.
Will try to see if I can fix it when I have time!

**Comment by vunguyen-dmt** [comment]
> Can you update `src/data/constants/app.test.js`?
> 
> ```js
> import * as platform from '@edx/frontend-platform';
> import * as constants from './app';
> 
> jest.unmock('./app');
> 
> jest.mock('@edx/frontend-platform', () => {
>   const PUBLIC_PATH = '/test-public-path/';
>   return {
>     getConfig: () => ({ PUBLIC_PATH }),
>     PUBLIC_PATH,
>   };
> });
> 
> describe('app constants', () => {
>   test('route path draws from public path and adds courseId', () => {
>     expect(constants.routePath()).toEqual(`${platform.PUBLIC_PATH}:courseId`);
>   });
>   describe('locationId', () => { 
>     const domain = 'https://example.com';
> 
>     test('returns trimmed pathname', () => {
>       const old = window.location;
>       Object.defineProperty(window, "location", {
>         value: new URL(`${domain}${platform.PUBLIC_PATH}somePath.jpg`),
>         writable: true,
>       });
>       expect(constants.locationId()).toEqual(window.location.pathname.replace(platform.PUBLIC_PATH, ''));
>       window.location = old;
>     });
>     test('handle none-standard characters pathName', () => {
>       const old = window.location;
>       const noneStandardPath = `${platform.PUBLIC_PATH}ORG+%C4%90+2023`;
>       const expectedPath = `${platform.PUBLIC_PATH}ORG+Đ+2023`;
>       Object.defineProperty(window, "location", {
>         value: new URL(`${domain}${noneStandardPath}`),
>         writable: true,
>       });
>       expect(noneStandardPath).not.toEqual(expectedPath);
>       expect(constants.locationId()).toEqual(expectedPath.replace(platform.PUBLIC_PATH, ''));
>       window.location = old;
>     });
>   });
> });
> ```

I've copied these code to apps.test.js. Is there anything else?
Sorry for the long delay!

**Comment by mphilbrick211** [comment]
Hi @leangseu-edx! Would you be able to help with the author's question, and re-enable checks to run?

**Comment by openedx-webhooks** [comment]
@vunguyen-dmt 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-ora-grading&entry.867055334=https://github.com/openedx/frontend-app-ora-grading/pull/189&entry.1484655318=https://github.com/vunguyen-dmt&entry.752974735=2023-06-08+03:31&entry.1917517419=2023-10-10+15:30&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
