### PR TITLE
[Palm] feat: Support runtime configuration

### PR DESCRIPTION
**Pull request by arbrandes**
This is a backport to `palm.master` of https://github.com/openedx/frontend-app-ora-grading/pull/183.

### CODE REVIEW

**Comment by arbrandes** [comment]
@ghassanmas, @dcoa, and @mafermazu, as reviewers of https://github.com/openedx/frontend-app-ora-grading/pull/183, care to give this one a thumbs up?

**Comment by MaferMazu** [comment]
@arbrandes, do we need to remove the src/config/index.js file?

**Comment by arbrandes** [comment]
@MaferMazu 
> do we need to remove the src/config/index.js file?

Ah, nice catch!

**Comment by arbrandes** [comment]
Oh, wait, it's already removed!

Edit: yes, we should remove it, as it's not being used anywhere anymore.

**Review by MaferMazu — APPROVED** [review]

**Pull request merged**
