### PR TITLE
fix: location id error

### PR DESCRIPTION
**Pull request by vunguyen-dmt**
The current code is wrong for this case (localtion id contains characters like: **Đ**) :
https://apps.demo.openedx.overhang.io/ora-grading/block-v1:ORG+Đ001+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f

Current code:
```
window.location.pathname.replace(getConfig().PUBLIC_PATH, '') = 
block-v1:ORG+%C4%90+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f
```

This PR code
```
decodeURIComponent(window.location.pathname).replace('/ora-grading/', '') =
block-v1:ORG+Đ+2023+type@openassessment+block@14709d5612014c57befb3c278b3b9b4f
```

The localtionId is used in [initialize request](https://github.com/openedx/frontend-app-ora-grading/blob/master/src/data/services/lms/api.js)
{LMS_BASE_URL}/api/ora_staff_grader/initialize?oraLocation={locationId}

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vunguyen-dmt!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @vunguyen-dmt! Thank you for your contribution. Please let me know if you have any questions regarding filling out the [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base). Thanks!

**Comment by e0d** [comment]
@vunguyen-dmt thanks for the contribution.  We'll need a CLA on file for you.  The instructions are in a comment above.

I also notice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by openedx-webhooks** [comment]
@vunguyen-dmt Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-ora-grading&entry.867055334=https://github.com/openedx/frontend-app-ora-grading/pull/186&entry.1484655318=https://github.com/vunguyen-dmt&entry.752974735=2023-06-03+11:11&entry.1917517419=2023-06-08+03:07&entry.2133058324=No) so we can improve your experience in the future.

**Comment by vunguyen-dmt** [comment]
Closed and created a new PR https://github.com/openedx/frontend-app-ora-grading/pull/189

**Pull request closed without merging**
