### PR TITLE
fix: wrong input argument in ErrorBanner

### LINKED ISSUE #285: ORA grading not displaying ORAs with file uploads
### Bug Description
Hi. I'm running openedx palm 3 with tutor. Recently I found that when trying to open an ORA with file upload by clicking on the "View all responses" button, the frontend crashes, displaying the page below:

image

When using a low speed internet connection, you can get a glance of the ORA app but then the said page will be displayed within a second. Diving more into the issue, I realised that the actual error is coming from the file preview part and then later when trying to show the error banner, another error occurs which is what we see in the screenshot above.

### How to reproduce
1. On a palm 3 installation of openedx, head to studio. Create an open response unit with optional or required file upload.
To do so, create a course and then a section and subsection. Within the subsection create a unit and choose "Open Response" component.

image

Choose one of the types (I chose staff review assessment). Then click on the "Edit" button on top of the component. 

image

Then on the "Settings" tab, enable file upload by making it either "Required" or "Optional".

image

2. Save and publish your changes. Head to LMS by clicking on "View live version" button. Add your response and a file 
to the ORA. Upload the file and submit the ORA. 

3. Now for grading, with a staff access, click on the "Grade available responses" button at the bottom of the unit.

image

4. In the opened page click on the "View all responses" button on top right to get the error page.

image

### Environment 
OpenedX Palm 3
Tutor 16.1.5
Ubuntu 22.04

### Additional context
The issue was originally [posted on openedx forum](https://discuss.openedx.org/t/ora-grading-returns-error/11482).

### PR DESCRIPTION
**Pull request by FatemeKhodayari**
When opening an ORA with file uploads, the MFE tries to preview the uploaded file. If anything goes wrong, it displays the error banner.

```js
...
  return (
    <FileCard key={file.downloadUrl} file={file}>
      {isLoading && <LoadingBanner />}
      {errorStatus ? (
        <ErrorBanner {...error} />
      ) : (
        <Renderer {...rendererProps} />
      )}
    </FileCard>
  );
...
```

As we see in the code, `error` is passed to `ErrorBanner` for displaying the error banner component. The `ErrorBanner` component has an input argument named `headingMessage`

```js
...
export const ErrorBanner = ({ actions, headerMessage, children }) => {
...
``` 

The problem happens here. The `error` object passed from the `FileRenderer` component has no `headingMessage` attribute. This will crash the frontend as it tries to get an `id` out of the `headingMessage` to display the translated error message. The attribute available in `error` is `headerMessage`. Renaming the input argument will fix this issue.

### Test Plan
To reproduce the error

1. Head to studio and create an ORA with file submissions
2. Open the ORA in LMS. Upload a file and submit the ORA
3. At the bottom of the unit in LMS, click on `Grade available responses` 
4. Log the `error` object in `FileRenderer` component for testing purpose or make some change that crashes the `FileRenderer` component
5. Click on `View all responses` button 

### Additional info
More info can be found in [this topic](https://discuss.openedx.org/t/ora-grading-returns-error/11482)

Closes [285](https://github.com/openedx/frontend-app-ora-grading/issues/285)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @FatemeKhodayari!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/openedx-unmaintained`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Comment by e0d** [comment]
@FatemeKhodayari looks like there are some check failing, can you have a look?

**Comment by FatemeKhodayari** [comment]
> @FatemeKhodayari looks like there are some check failing, can you have a look?

Sorry. I had forgotten to change the test file as well. Fixed it.

**Comment by mphilbrick211** [comment]
Hi @openedx/content-aurora  - this is ready for review. Thanks!

**Comment by FatemeKhodayari** [comment]
> Hi @openedx/content-aurora - this is ready for review. Thanks!

Dear @mphilbrick211, do you have any idea about the state of this PR? It's been open for so long that now it has conflict with the master branch :)) Shall I resolve the conflict so you can proceed with the review or maybe there's a problem with this PR and thus it won't be merged?

**Comment by mphilbrick211** [comment]
Hi @FatemeKhodayari! I apologize for the delay. I believe the Aurora group is no longer reviewing pull requests, so I will look into another reviewer for you. Ok to hold off on the conflict until we have a reviewer!

**Comment by FatemeKhodayari** [comment]
> Hi @FatemeKhodayari! I apologize for the delay. I believe the Aurora group is no longer reviewing pull requests, so I will look into another reviewer for you. Ok to hold off on the conflict until we have a reviewer!

Hi @mphilbrick211! No worries :) Thanks for looking into this. I'll wait to hear back from you before proceeding with the conflict.

**Review by arbrandes — CHANGES_REQUESTED** [review]
Every other instance of error handling in this MFE uses `headingMessage` for similar purposes.  I believe we should stick to that pattern.

With that in mind, do you mind changing https://github.com/openedx/frontend-app-ora-grading/blob/master/src/components/FilePreview/hooks.js#L82 instead?

**Comment by FatemeKhodayari** [comment]
> Every other instance of error handling in this MFE uses `headingMessage` for similar purposes. I believe we should stick to that pattern.
> 
> With that in mind, do you mind changing https://github.com/openedx/frontend-app-ora-grading/blob/master/src/components/FilePreview/hooks.js#L82 instead?

Thanks Adolfo. Applied the requested changes. Sorry for the messy git history by the way. Didn't squash / rebase the commits as I was afraid it may cause more conflict / complexity. Hope you can squash them while merging.

**Comment by mphilbrick211** [comment]
@arbrandes - would you mind re-enabling the tests to run?

**Comment by mphilbrick211** [comment]
Friendly ping on this, @arbrandes!

**Comment by mphilbrick211** [comment]
> Friendly ping on this, @arbrandes!

@arbrandes flagging for when you're able to take a look.

**Comment by CodeWithEmad** [comment]
We can close this in favor of https://github.com/openedx/frontend-app-ora-grading/commit/2208737a69bfe420f04a41b7d546ad82869b3d22

**Pull request closed without merging**
