### PR TITLE
[DOCS] Readme updated according OEP-55

### PR DESCRIPTION
**Pull request by johnvente**
The README of the MFE's need to be updated because the frontend app template has been updated.

Issue related: https://github.com/openedx/wg-frontend/issues/169

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @johnvente!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @openedx/content-aurora! Would someone be able to review and merge this for us? Thanks!

**Review by muselesscreator — APPROVED** [review]
lgtm

**Review by mattcarter — APPROVED** [review]
Approved.  Thank you!

**Comment by mphilbrick211** [comment]
Hi @johnvente!! Looks like a failing test has popped up - would you mind taking a look?

**Comment by johnvente** [comment]
> Hi @johnvente!! Looks like a failing test has popped up - would you mind taking a look?

Hey @mattcarter @muselesscreator! do know what could it be with the pipeline? I'm just updating the readme file, it looks like an error with the linter but it is weird

**Comment by mphilbrick211** [comment]
> > Hi @johnvente!! Looks like a failing test has popped up - would you mind taking a look?
> 
> Hey @mattcarter @muselesscreator! do know what could it be with the pipeline? I'm just updating the readme file, it looks like an error with the linter but it is weird

Hi @mattcarter and @muselesscreator! Just flagging this for you :)

**Comment by mphilbrick211** [comment]
> > > Hi @johnvente!! Looks like a failing test has popped up - would you mind taking a look?
> > 
> > 
> > Hey @mattcarter @muselesscreator! do know what could it be with the pipeline? I'm just updating the readme file, it looks like an error with the linter but it is weird
> 
> Hi @mattcarter and @muselesscreator! Just flagging this for you :)

Following up on this @mattcarter and @muselesscreator.

**Comment by mattcarter** [comment]
> > > > Hi @johnvente!! Looks like a failing test has popped up - would you mind taking a look?
> > > 
> > > 
> > > Hey @mattcarter @muselesscreator! do know what could it be with the pipeline? I'm just updating the readme file, it looks like an error with the linter but it is weird
> > 
> > 
> > Hi @mattcarter and @muselesscreator! Just flagging this for you :)
> 
> Following up on this @mattcarter and @muselesscreator.

That is weird!  I also see the branch is out of date; I'm rebasing, a quick check to see if that clears the error.

**Comment by mattcarter** [comment]
> > > > > Hi @johnvente!! Looks like a failing test has popped up - would you mind taking a look?
> > > > 
> > > > 
> > > > Hey @mattcarter @muselesscreator! do know what could it be with the pipeline? I'm just updating the readme file, it looks like an error with the linter but it is weird
> > > 
> > > 
> > > Hi @mattcarter and @muselesscreator! Just flagging this for you :)
> > 
> > 
> > Following up on this @mattcarter and @muselesscreator.
> 
> That is weird! I also see the branch is out of date; I'm rebasing, a quick check to see if that clears the error.

That did it. This is all approved, I'm going to merge it.

**Comment by openedx-webhooks** [comment]
@johnvente 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-ora-grading&entry.867055334=https://github.com/openedx/frontend-app-ora-grading/pull/194&entry.1484655318=https://github.com/johnvente&entry.752974735=2023-06-28+19:54&entry.1917517419=2023-09-12+17:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
